image: ubuntu:25.04

stages:        
  - build

build-job:
  stage: build
  script:
    - apt-get update
    - apt-get install -y python3.10 python3.10-venv python3-pip build-essential git
    - python3.10 -m venv .venv
    - . .venv/bin/activate
    - pip install --upgrade pip wheel setuptools
    - pip install -r requirements.txt
    - pip install pyinstaller
